name: 💁🏽‍♀️ Add an event for maintainers to the calendar 🎙
description: Use this form to add an event for maintainers or highlighting maintainers to the Maintainer Month calendar.
title: 'EVENT_NAME'

body:
  - type: markdown
    attributes:
      value: |
        :tada: Thanks for letting us know about an upcoming event! :tada:

        Use this form to add an event for maintainers or highlighting maintainers to the Maintainer Month calendar. Your request will be reviewed within 72 hours.

  - id: eventname
    type: input
    attributes:
      label: Event Name
    validations:
      required: true

  - id: date
    type: input
    attributes:
      label: Event Date
      placeholder: 'MM/DD'
    validations:
      required: true

  - id: endDate
    type: input
    attributes:
      label: Event End Date
      placeholder: 'MM/DD'
    validations:
      required: false

  - id: UTCStartTime
    type: input
    attributes:
      label: Start time in UTC
      placeholder: '14:00'
    validations:
      required: true

  - id: UTCEndTime
    type: input
    attributes:
      label: End time in UTC
      placeholder: '15:00'
    validations:
      required: true

  - id: type
    type: dropdown
    attributes:
      label: Event Type
      description: 'Type of event'
      options:
        - conference
        - podcast
        - stream
        - talk
        - meetup
        - fundraising
        - misc
    validations:
      required: true

  - id: language
    type: input
    attributes:
      label: Event Language
      description: 'Primary language of the event (e.g., English, Spanish, Mandarin)'
    validations:
      required: true

  - id: location
    type: input
    attributes:
      label: Event Location
      description: 'Primary location of the event - either Virtual or a City + Country'
    validations:
      required: true

  - id: userName
    type: input
    attributes:
      label: Organizer name
      description: Organizer name
    validations:
      required: true

  - id: linkUrl
    type: input
    attributes:
      label: Event URL
      description: 'Web URL of event'
      placeholder: 'https://'

  - id: eventdescription
    type: textarea
    attributes:
      label: Event Description
      description: 'What is this event about?'

  - id: expectedparticipants
    type: input
    attributes:
      label: Participants
      description: 'Expected number of participants'
      placeholder: '###'

  - id: expectedmaintainers
    type: input
    attributes:
      label: Maintainers
      description: 'Expected number of maintainers participating'
      placeholder: '###'
